---
- name: Install and verify Apache Web Server on Amazon Linux
  hosts: tag_acs730
  become: yes
  gather_facts: True
  vars:
    ansible_user: ec2-user 
    ansible_ssh_private_key_file: /home/ec2-user/environment/terraform/webserver/access_key
    image_source: /home/ec2-user/environment/ansiblefinal/Project_Architecture_Diagram.png
    image_dest: /var/www/html/Project_Architecture_Diagram.png
    env: prod


  tasks:
    - name: Install Apache on Amazon Linux
      yum:
        name: httpd
        state: latest

    - name: Start and enable Apache service on Amazon Linux
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Wait for Apache to start
      wait_for:
        port: 80
        state: started
        delay: 5
        timeout: 30
    
    - name: Deploy dynamic index.html using Jinja2 template
      template:
        src: ./index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart Httpd

      
    - name: Copy Image file
      copy:
        src: "{{ image_source }}"
        dest: "{{ image_dest }}"
        mode: '0644'
      notify: Restart Httpd
      
    
  handlers:
    - name: Restart Httpd
      service:
        name: httpd
        state: restarted
