---
- name: Download image from S3 to Cloud9
  hosts: localhost
  tasks:
    - name: Download file from S3
      amazon.aws.aws_s3:
        bucket: acs730-final-group-project-bucket
        object: Project_Architecture_Diagram.png
        dest: /home/ec2-user/environment/ansiblefinal/Project_Architecture_Diagram.png
        mode: get
        region: us-east-1