name: Terraform CI/CD for Network and Webserver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact

  terraform-network:
    needs: security-scans
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Network)
        run: terraform init
        working-directory: terraform/network

      - name: Terraform Validate (Network)
        run: terraform validate
        working-directory: terraform/network

      - name: Terraform Plan (Network)
        run: terraform plan -out=tfplan
        working-directory: terraform/network

      - name: Terraform Apply (Network)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/network

      - name: Network Approval
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "Network infrastructure changes have been applied"

  terraform-webserver:
    needs: terraform-network
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Webserver)
        run: terraform init
        working-directory: terraform/webserver

      - name: Terraform Validate (Webserver)
        run: terraform validate
        working-directory: terraform/webserver

      - name: Terraform Plan (Webserver)
        run: terraform plan -out=tfplan
        working-directory: terraform/webserver

      - name: Terraform Apply (Webserver)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/webserver

      - name: Webserver Approval
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "Webserver infrastructure changes have been applied"
